const cards = [
  { number: 1, ipa: "/ɪ/", example_en: "bit", example_ru: "бит", lifehack: "Как короткое 'и'" , audio: "i.mp3" },
  { number: 2, ipa: "/iː/", example_en: "sheep", example_ru: "овца", lifehack: "Долгое 'иии'" , audio: "ii.mp3" },
  { number: 3, ipa: "/ɒ/", example_en: "dot", example_ru: "точка", lifehack: "Короткое 'о'" , audio: "o.mp3" },
  { number: 4, ipa: "/ɔː/", example_en: "law", example_ru: "закон", lifehack: "Долгое 'ооо'" , audio: "oo.mp3" },
  { number: 5, ipa: "/e/", example_en: "bed", example_ru: "кровать", lifehack: "Как 'э'" , audio: "e.mp3" },
  { number: 6, ipa: "/æ/", example_en: "cat", example_ru: "кот", lifehack: "Что-то между 'э' и 'а'" , audio: "a.mp3" },
  { number: 7, ipa: "/ʌ/", example_en: "cup", example_ru: "чашка", lifehack: "Короткое 'а'" , audio: "u.mp3" },
  { number: 8, ipa: "/ɑː/", example_en: "car", example_ru: "машина", lifehack: "Долгое 'ааа'" , audio: "ah.mp3" },
  { number: 9, ipa: "/ə/", example_en: "banana", example_ru: "банан", lifehack: "Очень короткий безударный звук" , audio: "uh.mp3" },
  { number: 10, ipa: "/ɜː/", example_en: "bird", example_ru: "птица", lifehack: "Что-то между 'ё' и 'о'" , audio: "ur.mp3" },
  { number: 11, ipa: "/ʊ/", example_en: "book", example_ru: "книга", lifehack: "Короткое 'у'" , audio: "oo_short.mp3" },
  { number: 12, ipa: "/eə/", example_en: "air", example_ru: "воздух", lifehack: "Ээ + р" , audio: "air.mp3" },
  { number: 13, ipa: "/ɪə/", example_en: "ear", example_ru: "ухо", lifehack: "И + э" , audio: "ear.mp3" },
  { number: 14, ipa: "/eɪ/", example_en: "day", example_ru: "день", lifehack: "Эй" , audio: "ei.mp3" },
  { number: 15, ipa: "/əʊ/", example_en: "go", example_ru: "идти", lifehack: "Оу" , audio: "ou.mp3" },
  { number: 16, ipa: "/aʊ/", example_en: "now", example_ru: "сейчас", lifehack: "Ау" , audio: "ow.mp3" },
  { number: 17, ipa: "/ɔɪ/", example_en: "boy", example_ru: "мальчик", lifehack: "Ой" , audio: "oi.mp3" },
  { number: 18, ipa: "/ʊə/", example_en: "tour", example_ru: "тур", lifehack: "Уэ" , audio: "ure.mp3" },
  { number: 19, ipa: "/juː/", example_en: "music", example_ru: "музыка", lifehack: "Ю" , audio: "ju.mp3" },
  { number: 20, ipa: "/ɑː/", example_en: "father", example_ru: "отец", lifehack: "Долгое 'а'" , audio: "aa.mp3" },
  // остальные согласные звуки аналогично (если хочешь — продолжу)
];
