const cards = [
  { number: 1, ipa: "/ɪ/", transcription: "[ɪ]", example_en: "bit", example_ru: "бит", lifehack: "Короткое 'и'", audio: "i.mp3" },
  { number: 2, ipa: "/iː/", transcription: "[iː]", example_en: "sheep", example_ru: "овца", lifehack: "Долгое 'иии'", audio: "ii.mp3" },
  { number: 3, ipa: "/ɒ/", transcription: "[ɒ]", example_en: "dot", example_ru: "точка", lifehack: "Короткое 'о'", audio: "o.mp3" },
  { number: 4, ipa: "/ɔː/", transcription: "[ɔː]", example_en: "law", example_ru: "закон", lifehack: "Долгое 'ооо'", audio: "oo.mp3" },
  { number: 5, ipa: "/e/", transcription: "[e]", example_en: "bed", example_ru: "кровать", lifehack: "Как 'э'", audio: "e.mp3" },
  { number: 6, ipa: "/æ/", transcription: "[æ]", example_en: "cat", example_ru: "кот", lifehack: "Что-то между 'э' и 'а'", audio: "a.mp3" },
  { number: 7, ipa: "/ʌ/", transcription: "[ʌ]", example_en: "cup", example_ru: "чашка", lifehack: "Короткое 'а'", audio: "u.mp3" },
  { number: 8, ipa: "/ɑː/", transcription: "[ɑː]", example_en: "car", example_ru: "машина", lifehack: "Долгое 'ааа'", audio: "ah.mp3" },
  { number: 9, ipa: "/ə/", transcription: "[ə]", example_en: "banana", example_ru: "банан", lifehack: "Очень короткий безударный звук", audio: "uh.mp3" },
  { number: 10, ipa: "/ɜː/", transcription: "[ɜː]", example_en: "bird", example_ru: "птица", lifehack: "Похоже на 'ё' в английском", audio: "ur.mp3" },
  { number: 11, ipa: "/ʊ/", transcription: "[ʊ]", example_en: "book", example_ru: "книга", lifehack: "Короткое 'у'", audio: "oo_short.mp3" },
  { number: 12, ipa: "/eə/", transcription: "[eə]", example_en: "air", example_ru: "воздух", lifehack: "Ээ + э", audio: "air.mp3" },
  { number: 13, ipa: "/ɪə/", transcription: "[ɪə]", example_en: "ear", example_ru: "ухо", lifehack: "И + э", audio: "ear.mp3" },
  { number: 14, ipa: "/eɪ/", transcription: "[eɪ]", example_en: "day", example_ru: "день", lifehack: "Эй", audio: "ei.mp3" },
  { number: 15, ipa: "/əʊ/", transcription: "[əʊ]", example_en: "go", example_ru: "идти", lifehack: "Оу", audio: "ou.mp3" },
  { number: 16, ipa: "/aʊ/", transcription: "[aʊ]", example_en: "now", example_ru: "сейчас", lifehack: "Ау", audio: "ow.mp3" },
  { number: 17, ipa: "/ɔɪ/", transcription: "[ɔɪ]", example_en: "boy", example_ru: "мальчик", lifehack: "Ой", audio: "oi.mp3" },
  { number: 18, ipa: "/ʊə/", transcription: "[ʊə]", example_en: "tour", example_ru: "тур", lifehack: "Уэ", audio: "ure.mp3" },
  { number: 19, ipa: "/juː/", transcription: "[juː]", example_en: "music", example_ru: "музыка", lifehack: "Ю", audio: "ju.mp3" },
  { number: 20, ipa: "/ɑː/", transcription: "[ɑː]", example_en: "father", example_ru: "отец", lifehack: "Долгое 'а'", audio: "aa.mp3" },
];
cards.push(
  { number: 21, ipa: "/b/", transcription: "[b]", example_en: "bat", example_ru: "летучая мышь", lifehack: "Буква Б", audio: "b.mp3" },
  { number: 22, ipa: "/d/", transcription: "[d]", example_en: "dog", example_ru: "собака", lifehack: "Буква Д", audio: "d.mp3" },
  { number: 23, ipa: "/f/", transcription: "[f]", example_en: "fish", example_ru: "рыба", lifehack: "Ф", audio: "f.mp3" },
  { number: 24, ipa: "/g/", transcription: "[g]", example_en: "go", example_ru: "идти", lifehack: "Г", audio: "g.mp3" },
  { number: 25, ipa: "/h/", transcription: "[h]", example_en: "house", example_ru: "дом", lifehack: "Х (выдох)", audio: "h.mp3" },
  { number: 26, ipa: "/j/", transcription: "[j]", example_en: "yes", example_ru: "да", lifehack: "Й", audio: "j.mp3" },
  { number: 27, ipa: "/k/", transcription: "[k]", example_en: "cat", example_ru: "кот", lifehack: "К", audio: "k.mp3" },
  { number: 28, ipa: "/l/", transcription: "[l]", example_en: "love", example_ru: "любовь", lifehack: "Л", audio: "l.mp3" },
  { number: 29, ipa: "/m/", transcription: "[m]", example_en: "man", example_ru: "мужчина", lifehack: "М", audio: "m.mp3" },
  { number: 30, ipa: "/n/", transcription: "[n]", example_en: "net", example_ru: "сеть", lifehack: "Н", audio: "n.mp3" },
  { number: 31, ipa: "/ŋ/", transcription: "[ŋ]", example_en: "song", example_ru: "песня", lifehack: "Нг", audio: "ng.mp3" },
  { number: 32, ipa: "/p/", transcription: "[p]", example_en: "pen", example_ru: "ручка", lifehack: "П", audio: "p.mp3" },
  { number: 33, ipa: "/r/", transcription: "[r]", example_en: "red", example_ru: "красный", lifehack: "Р (мягкий)", audio: "r.mp3" },
  { number: 34, ipa: "/s/", transcription: "[s]", example_en: "sun", example_ru: "солнце", lifehack: "С", audio: "s.mp3" },
  { number: 35, ipa: "/ʃ/", transcription: "[ʃ]", example_en: "she", example_ru: "она", lifehack: "Ш", audio: "sh.mp3" },
  { number: 36, ipa: "/t/", transcription: "[t]", example_en: "top", example_ru: "верх", lifehack: "Т", audio: "t.mp3" },
  { number: 37, ipa: "/tʃ/", transcription: "[tʃ]", example_en: "chat", example_ru: "болтать", lifehack: "Ч", audio: "ch.mp3" },
  { number: 38, ipa: "/θ/", transcription: "[θ]", example_en: "think", example_ru: "думать", lifehack: "Зубной С", audio: "th_voiceless.mp3" },
  { number: 39, ipa: "/ð/", transcription: "[ð]", example_en: "this", example_ru: "это", lifehack: "Зубной З", audio: "th_voiced.mp3" },
  { number: 40, ipa: "/v/", transcription: "[v]", example_en: "voice", example_ru: "голос", lifehack: "В", audio: "v.mp3" },
  { number: 41, ipa: "/w/", transcription: "[w]", example_en: "water", example_ru: "вода", lifehack: "У-в", audio: "w.mp3" },
  { number: 42, ipa: "/z/", transcription: "[z]", example_en: "zoo", example_ru: "зоопарк", lifehack: "З", audio: "z.mp3" },
  { number: 43, ipa: "/ʒ/", transcription: "[ʒ]", example_en: "vision", example_ru: "видение", lifehack: "Ж", audio: "zh.mp3" },
  { number: 44, ipa: "/dʒ/", transcription: "[dʒ]", example_en: "jam", example_ru: "варенье", lifehack: "Дж", audio: "dj.mp3" },
  { number: 45, ipa: "/ʔ/", transcription: "[ʔ]", example_en: "uh-oh", example_ru: "ой!", lifehack: "Гортанный хлопок", audio: "glottal.mp3" }
);
