const cards = [
  { number: 1, ipa: "/ɪ/", example_en: "bit", example_ru: "фильм", lifehack: "Короткое 'и', как в 'мир', мягко." },
  { number: 2, ipa: "/iː/", example_en: "sheep", example_ru: "тим", lifehack: "Долгое 'и', тянуть улыбаясь: 'иии'." },
  { number: 3, ipa: "/ɒ/", example_en: "dot", example_ru: "стоп", lifehack: "Короткое 'о', губы округлить, как 'о!'." },
  { number: 4, ipa: "/ɔː/", example_en: "fork", example_ru: "спорт", lifehack: "Долгое 'о', как в 'ооо'." },
  { number: 5, ipa: "/e/", example_en: "jet", example_ru: "альф", lifehack: "Короткое 'э', чётко, как 'мэр'." },
  { number: 6, ipa: "/æ/", example_en: "fat", example_ru: "сэндвич", lifehack: "Широкий рот, смесь 'а' и 'э', как 'мяу'." },
  { number: 7, ipa: "/ʌ/", example_en: "cup", example_ru: "компания", lifehack: "Тусклое 'а', нейтральное." },
  { number: 8, ipa: "/ɑː/", example_en: "car", example_ru: "маска", lifehack: "Долгое 'ааа', язык внизу." },
  { number: 9, ipa: "/ə/", example_en: "about", example_ru: "монстр", lifehack: "Безударное 'э', почти не слышно." },
  { number: 10, ipa: "/ɜː/", example_en: "girl", example_ru: "девочка", lifehack: "Как 'ёр', с напряжением." },
  { number: 11, ipa: "/ʊ/", example_en: "put", example_ru: "футбол", lifehack: "Короткое 'у', губы округлены." },
  { number: 12, ipa: "/uː/", example_en: "goose", example_ru: "шут", lifehack: "Долгое 'ууу', вытянуть губы вперёд." },
  { number: 13, ipa: "/juː/", example_en: "new", example_ru: "компьютер", lifehack: "'йу', как 'йогурт'." },
  { number: 14, ipa: "/eɪ/", example_en: "cake", example_ru: "безопасный", lifehack: "'эй', как 'окей'." },
  { number: 15, ipa: "/aɪ/", example_en: "ice", example_ru: "айсберг", lifehack: "'ай', как 'ай-яй-яй'." },
  { number: 16, ipa: "/ɔɪ/", example_en: "boy", example_ru: "бойскаут", lifehack: "'ой', как при удивлении." },
  { number: 17, ipa: "/ɪə/", example_en: "beer", example_ru: "пиво", lifehack: "'ие', как 'где я'." },
  { number: 18, ipa: "/eə/", example_en: "bear", example_ru: "аэроплан", lifehack: "'эа', как 'мэр' с 'а'." },
  { number: 19, ipa: "/ʊə/", example_en: "poor", example_ru: "турист", lifehack: "'уэ', как 'у-а' слитно." },
  { number: 20, ipa: "/əʊ/", example_en: "go", example_ru: "шоу", lifehack: "'оу', как 'ноу'." },
  { number: 21, ipa: "/aʊ/", example_en: "mouse", example_ru: "мышь", lifehack: "'ау', как 'ау, больно'." },
  { number: 22, ipa: "/p/", example_en: "pizza", example_ru: "пицца", lifehack: "Глухой 'п', с резким выдохом." },
  { number: 23, ipa: "/b/", example_en: "banana", example_ru: "банан", lifehack: "Звонкий 'б', мягкий." },
  { number: 24, ipa: "/k/", example_en: "kangaroo", example_ru: "кенгуру", lifehack: "Глухой 'к', из глубины." },
  { number: 25, ipa: "/g/", example_en: "gorilla", example_ru: "горилла", lifehack: "Звонкий 'г'." },
  { number: 26, ipa: "/f/", example_en: "finish", example_ru: "финш", lifehack: "Глухой 'ф', зубы на губе, воздух." },
  { number: 27, ipa: "/v/", example_en: "villa", example_ru: "вилла", lifehack: "Звонкий 'в' с вибрацией." },
  { number: 28, ipa: "/t/", example_en: "tractor", example_ru: "трактор", lifehack: "Глухой 'т', резко." },
  { number: 29, ipa: "/d/", example_en: "doctor", example_ru: "доктор", lifehack: "Звонкий 'д'." },
  { number: 30, ipa: "/s/", example_en: "sofa", example_ru: "софа", lifehack: "Глухой 'с', шипит." },
  { number: 31, ipa: "/z/", example_en: "zebra", example_ru: "зебра", lifehack: "Звонкий 'з', как 'ззз'." },
  { number: 32, ipa: "/ʃ/", example_en: "shorts", example_ru: "шорты", lifehack: "Глухой 'ш', округлить губы." },
  { number: 33, ipa: "/ʒ/", example_en: "mirage", example_ru: "гараж", lifehack: "Звонкий 'ж', мягкий." },
  { number: 34, ipa: "/θ/", example_en: "thin", example_ru: "спасибо", lifehack: "Межзубный 'с', язык между зубами." },
  { number: 35, ipa: "/ð/", example_en: "this", example_ru: "мама", lifehack: "Межзубный 'з', с голосом." },
  { number: 36, ipa: "/tʃ/", example_en: "chips", example_ru: "чипсы", lifehack: "Как 'ч', 'тш' вместе." },
  { number: 37, ipa: "/dʒ/", example_en: "jam", example_ru: "джем", lifehack: "Как 'дж', мягко." },
  { number: 38, ipa: "/l/", example_en: "lily", example_ru: "лилия", lifehack: "Боковой 'л', как 'лук'." },
  { number: 39, ipa: "/r/", example_en: "robot", example_ru: "робот", lifehack: "Как английское 'р', без трели." },
  { number: 40, ipa: "/w/", example_en: "wigwam", example_ru: "вигвам", lifehack: "Как 'в', губы округлить." },
  { number: 41, ipa: "/j/", example_en: "yogurt", example_ru: "йогурт", lifehack: "Как 'й', как в 'йога'." },
  { number: 42, ipa: "/m/", example_en: "music", example_ru: "музыка", lifehack: "Носовой 'м'." },
  { number: 43, ipa: "/n/", example_en: "nose", example_ru: "нос", lifehack: "Носовой 'н'." },
  { number: 44, ipa: "/ŋ/", example_en: "ping", example_ru: "пинг-понг", lifehack: "Как 'нг', без 'г'." },
  { number: 45, ipa: "/h/", example_en: "hat", example_ru: "хулиган", lifehack: "Как лёгкий выдох — 'х'." }
];
