const dictionary = {
  "cat": "[kæt]",
  "dog": "[dɒg]",
  "apple": "[ˈæpl]",
  "beautiful": "[ˈbjuːtɪfəl]",
  "music": "[ˈmjuːzɪk]",
  "car": "[kɑːr]",
  "cup": "[kʌp]",
  "banana": "[bəˈnɑːnə]",
  "father": "[ˈfɑːðər]",
  "school": "[skuːl]",
  "work": "[wɜːrk]",
  "book": "[bʊk]",
  "go": "[ɡəʊ]",
  "now": "[naʊ]",
  "boy": "[bɔɪ]",
  "tour": "[tʊə]",
  "day": "[deɪ]",
  "air": "[eə]",
  "ear": "[ɪə]",
  "bit": "[bɪt]",
  "sheep": "[ʃiːp]",
  "dot": "[dɒt]",
  "law": "[lɔː]",
  "bed": "[bed]",
  "bird": "[bɜːd]",
};
